# Generated by Django 5.0.9 on 2025-02-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заполняется автоматически', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(blank=True, help_text='Генерируется автоматически', null=True, upload_to='products/medium/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_thumbnail',
            field=models.ImageField(blank=True, help_text='Генерируется автоматически', null=True, upload_to='products/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заполняется автоматически', unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заполняется автоматически'),
        ),
    ]
